package com.fanren.lib.DAO;

import com.fanren.lib.pojo.history_info;
import com.fanren.lib.pojo.history_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface history_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    long countByExample(history_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    int deleteByExample(history_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    int insert(history_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    int insertSelective(history_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    List<history_info> selectByExample(history_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") history_info record, @Param("example") history_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    int updateByExample(@Param("record") history_info record, @Param("example") history_infoExample example);
}