package com.fanren.lib.pojo;

import java.util.Date;

public class history_info {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.Id
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.book_id
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.read_time
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    private Date readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.back_time
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    private Date backTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.people
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    private String people;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.Id
     *
     * @return the value of history.Id
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.Id
     *
     * @param id the value for history.Id
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.book_id
     *
     * @return the value of history.book_id
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.book_id
     *
     * @param bookId the value for history.book_id
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.read_time
     *
     * @return the value of history.read_time
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.read_time
     *
     * @param readTime the value for history.read_time
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.back_time
     *
     * @return the value of history.back_time
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public Date getBackTime() {
        return backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.back_time
     *
     * @param backTime the value for history.back_time
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public void setBackTime(Date backTime) {
        this.backTime = backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.people
     *
     * @return the value of history.people
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public String getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.people
     *
     * @param people the value for history.people
     *
     * @mbg.generated Sat Sep 08 10:01:13 CST 2018
     */
    public void setPeople(String people) {
        this.people = people == null ? null : people.trim();
    }
}